### ISSUE TITLE
Stworzenie tabeli 'SESSION' w bazie danych

### ISSUE THREAD

**Issue by AMordaka** [Cinema-project/Cinema#13]
Trzeba przedyskutować jakie dane mają być w tabeli SESSION.

**Comment by SharpShooter17** [comment]
Tabela ma wyglądać tak:

CREATE TABLE IF NOT EXISTS `ci_sessions` (
        `id` varchar(128) NOT NULL,
        `ip_address` varchar(45) NOT NULL,
        `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
        `data` blob NOT NULL,
        KEY `ci_sessions_timestamp` (`timestamp`)
);

Innego wyboru nie ma bo tak jest w CI - CodeIgniter.

Jedyne co to co ma być w polu blob,
Myślę, że można tam wrzucić czy klient jest zalogowany czy nie oraz jego id.

**Comment by SharpShooter17** [comment]
Z tym można się chwilowo wstrzymać...
