### ISSUE TITLE
iss-15 wprowadzenie współrzędnych kin do bazy

### ISSUE THREAD

**Issue by SharpShooter17** [Cinema-project/Cinema#43]

**Comment by lukabaca** [comment]
Skrypt dodawania współrzędnych kin 'kina_MultiKino.php' , który realizuje zadanie wrzuciłem luzem do głównego folderu. Póki co odpalić ręcznie by zobaczyć czy działa, pózniej można gdzieś wrzucić żeby automatycznie z odpalaniem projektu ten skrypt sie załączał.
